migtools/mta-documentation

- docs/topics/create-first-yaml-rule.adoc
- docs/topics/create-yaml-rule.adoc
- docs/topics/review-existing-rules.adoc
- docs/topics/rules-important-links.adoc
- docs/topics/templates/document-attributes.adoc
- docs/topics/testing-rules.adoc
- docs/topics/yaml-rule-structure-syntax.adoc
MTV 7.1 
https://github.com/windup/windup-documentation/pull/900 for MTV 7.1 . 
Resolves https://issues.redhat.com/browse/MTA-2919 by repairing 3 broken links in the Rules development guide and commenting out 1 that is irrelevant.
Also makes a number of small corrections to the guide:
Previews:
Broken links repaired:
https://file.emea.redhat.com/rhoch/71_broken_links_rules_dev/html-single/#test_xml_rule_syntax [Links in section for "InterableFilter," "ClassificationExists," and "HintsExist."]
Broken link commented out because the Java docs link on the windup website is broken:
https://file.emea.redhat.com/rhoch/71_broken_links_rules_dev/html-single/#rules-important-links_rules-development-guide [Link to "Javadocs" in Appendix 2.2 removed (commented out in rules-important-links.adoc)] …
> Fix broken links in MTV 7.1 Rules development guide

- snippets/developer-preview-admonition.adoc
- snippets/developer-preview.adoc
- snippets/technology-preview-admonition.adoc
- snippets/technology-preview.adoc
I left the `:FeatureName:` variable uncommented in the snippets file
It should be commented out, so people can use:
```
:FeatureName: This is our new feature
include::snippets/developer-preview-admonition.adoc[]
```
> Fixing missed comment in snippets

- docs/topics/mta-7-installing-web-console-on-openshift.adoc
* [MTA-3657](https://issues.redhat.com/browse/MTA-3657)
This is the old disconnected install section - replaced by https://docs.redhat.com/en/documentation/migration_toolkit_for_applications/7.1/html/cli_guide/installing_and_running_the_cli#installing-mta-disconnected-environment_cli-guide
> MTA-3657: Remove old disconnected installation section

- docs/topics/mta-web-adding-applications.adoc
* [MTA-4264](https://issues.redhat.com/browse/MTA-4264)
* [6.1. Adding a new application](https://anarnold97.github.io/MTA-Preview/MTA/MTA-4264-SVN-tags.html#mta-web-adding-applications_user-interface-guide)
| PREVIEW |
| ------------- |
| ![image](https://github.com/user-attachments/assets/c9d52c5e-0b62-49e9-9f7a-a004dda70d64) |
> To be merged for 7.1 - MTA-4264: Tags are inaccessible in SVN repositories

- docs/release-notes/master.adoc
- docs/topics/eclipse-configuring-run.adoc
- docs/topics/svn-checkout-fails-issue-snippet.adoc
* [MTA-4309](https://issues.redhat.com/browse/MTA-4309)
See - [Slack discussion](https://redhat-internal.slack.com/archives/C02FNEJ9PLZ/p1733249537975539)
Creating a snippet to add to 7.1 release notes in the PR and the rebase [7.2 release notes PR](https://github.com/migtools/mta-documentation/pull/67) and add snippet
> To be merged for 7.1 WIP - MTA-4309: SVN checkout fails added to 7.1 release notes

- docs/cli-guide/master.adoc
- docs/topics/installing-cli-tool.adoc
- docs/topics/installing-mta-disconnected-environment.adoc
- docs/topics/proc_running-the-containerless-mta-cli.adoc
Tracked under [MTA-3708](https://issues.redhat.com/browse/MTA-3708) and also worked on in the [gdoc draft](https://docs.google.com/document/d/1VWoMnQpZH9d_hZH_g1OgBsu5pP08QYVnUt4Ygjv1urc/edit?userstoinvite=emcmulla%40redhat.com&sharingaction=manageaccess&role=writer&tab=t.0#heading=h.ux36o96cqrnc).
[Current preview](https://mpershina.github.io/Previews/MTA/MTA-3708_1)
> [To be merged for 7.2] Containerless CLI procedure for 7.2.0

- docs/topics/mta-7-installing-web-console-on-openshift.adoc
* [MTA-4161](https://issues.redhat.com/browse/MTA-4161)
* [3. Installing the Migration Toolkit for Applications user interface](https://anarnold97.github.io/MTA-Preview/MTA/cr-flags.html#mta-7-installing-web-console-on-openshift_user-interface-guide)
> MTA-4161: Add missing configuration flags to Tackle CR

- docs/topics/installing-cli-tool.adoc
* [MTA-4628](https://issues.redhat.com/browse/MTA-4628)
[2.1.2. Installing the CLI by using Podman](https://anarnold97.github.io/MTA-Preview/MTA/mta-podman.html#installing-using-podman_cli-guide)
> ready to be merged - MTA-4628: Adding a link to podman configuration and setting

- docs/release-notes/master.adoc
- docs/topics/ref_known-issues-7-2-1.adoc
- docs/topics/ref_resolved-issues-7-2-1.adoc
Closes [MTA-3750](https://issues.redhat.com/browse/MTA-3750)
> to be merged - MTA 7.2.1 Release Notes

- docs/release-notes/master.adoc
There is a build error in the release notes
Line 45:
```
[id="mta-7-2-0"]
== {ProductShortName} 7.2.1
```
Duplicate ID, but it is not a major problem and i will get it fixed now
> MTA 7.2.1 release notes fix

- .github/workflows/lint-with-vale.yml
- vale.ini
* [MTA-4748](https://issues.redhat.com/browse/MTA-4748)
With this PR, I am adding a GitHub workflow action. 
I am adding a `vale.ini` at the root level of the repo and a `lint-with-vale.yml`, in the `.github/workflows` directory,  to define the workflow.
The `vale.ini` is set to include Red Hat styles and two other linters to improve grammar and spelling:
```
BasedOnStyles = RedHat, proselint, write-good
```
This is set to fire on `pull_request`
> MTA-4748: Adding Vale to MTA GitHub repo

- docs/topics/installing-cli-tool.adoc
* [MTA-4977](https://issues.redhat.com/browse/MTA-4977)
* [2.1.1. Installing the CLI .zip file](https://anarnold97.github.io/MTA-Preview/MTA/MTA-4977.html#installing-downloadable-cli-zip_cli-guide)
> MTA-4977: Correcting installing CLI zip to include CPU architecture packages

- docs/topics/mta-7-installing-web-console-on-openshift.adoc
* [MTA-4958](https://issues.redhat.com/browse/MTA-4958)
The CR settings table at the "Installing the Migration Toolkit for Applications Operator and the user interface" section reflects the following default values:
```
analyzer_container_requests_memory: 4Gi
analyzer_container_limits_memory: 4Gi
```
After checking, it has been found that the correct values are as follows:
```
analyzer_container_requests_memory: 1Gi
analyzer_container_limits_memory: 1Gi
```
* [3. Installing the Migration Toolkit for Applications user interface](https://anarnold97.github.io/MTA-Preview/MTA/MTA-4958.html#mta-7-installing-web-console-on-openshift_user-interface-guide)
> MTA-4958: Default memory values for the analyzer container are wrong

- docs/topics/installing-cli-tool.adoc
- docs/topics/proc_running-the-containerless-mta-cli.adoc
* [MTA-4662](https://issues.redhat.com/browse/MTA-4662)
* [2.3.4. Running the containerless CLI](https://anarnold97.github.io/MTA-Preview/MTA/containerless-cli.html#running-the-containerless-mta-cli_cli-guide)
> MTA-4662: Update containerless CLI docs

- docs/topics/ref_resolved-issues-7-3-0.adoc
* [MTA-5078 [Documentation for] When analyzing Maven project, there is difference before and after executing "mvn clean package"](https://issues.redhat.com/browse/MTA-5078)
* 7.3.0
> MTA-5078: Added a Resolved Issue for RN 7.3.0

- docs/topics/mta-cli-analyze.adoc
- docs/topics/mta-cli-args.adoc
- docs/topics/mta-cli-run-single-app.adoc
* [MTA-4798 Documentation for Support a new command in the CLI to return the language of the project](https://issues.redhat.com/browse/MTA-4798)
* 7.3.0
* [Running the MTA CLI against an application: Step 2](https://file.corp.redhat.com/pkylasam/mta-4798/html-single/#mta-cli-run-single-app_cli-guide)
* [Performing analysis using the command line: --list-language in flag list and procedure step 2](https://file.corp.redhat.com/pkylasam/mta-4798/html-single/#mta-cli-analyze_cli-guide)
* [A.1. About MTA command-line arguments](https://file.corp.redhat.com/pkylasam/mta-4798/html-single/#cli-args_cli-guide)
> MTA-4798: Support for Listing Languages in 7.3.0

- docs/topics/ref_known-issues-7-3-0.adoc
* [MTA-5094](https://issues.redhat.com/browse/MTA-5094)
* 7.3.0
> MTA-5094: [CLI] Analysis of non-java application tries to run in containerless mode

- README.md
Update the README.md file for the new mta-documentation repository.
Tracked under [MTA-2936](https://issues.redhat.com/browse/MTA-2936).
> [WIP] Updates to README.md

- docs/topics/mta-7-installing-web-console-on-openshift.adoc
Removed `rhsso_external_access` in the [Tackle CR Setting table](https://docs.redhat.com/en/documentation/migration_toolkit_for_applications/7.3/html/user_interface_guide/mta-7-installing-web-console-on-openshift_user-interface-guide#installing-mta-operator-and-ui_user-interface-guide).
> MTA 7.3.0: Removed rhsso_external_access in Tackle CR Setting

- docs/topics/mta-cli/ref_mta-cli-analyze-flags.adoc
* [MTA-5964](https://issues.redhat.com/browse/MTA-5964)
* 7.3.2
* [Added --disable-maven-search](https://pkylas007.github.io/Preview/MTA/mta-5964/index.html#mta-cli-analyze-flags_analyzing-applications-mta-cli)
> MTA-5964 - Added --disable-maven-search flag in CLI guide

- docs/release-notes/master.adoc
- docs/topics/mta-rn-technical-changes-7-3-2.adoc
- docs/topics/ref_fixed-issues-7-3-2.adoc
- docs/topics/ref_known-issues-7-3-2.adoc
* [MTA-5305](https://issues.redhat.com/browse/MTA-5305)
* 7.3.2
* [Release notes for 7.3.2](https://pkylas007.github.io/Preview/MTA/mta-5305/index.html#mta-7-3-2)
> MTA-5305 Release Notes for 7.3.2

- docs/topics/templates/document-attributes.adoc
Tracked under [MTA-5304](https://issues.redhat.com/browse/MTA-5304).
Checked the OCP versions in the [spreadsheet](https://docs.google.com/spreadsheets/d/19bRYespPb-AvclkwkoizmJ6NZ54p9iFRn6DGD8Ugv2c/edit?gid=1587698867#gid=1587698867) as well. No change to the attributes as of now.
> Attributes updates for MTA 7.3.2
