migtools/mta-documentation

docs/topics/templates/document-attributes.adoc
* [MTA-3625](https://issues.redhat.com/browse/MTA-3625): Values to test the build of MTA 7.1.0. Changing the main attributes to 7.1 as required by Pantheon
=> MTA-3625: Dummy attributes for MTA sync and merge test

docs/cli-guide/master.adoc, docs/topics/about-cli-guide.adoc, docs/topics/developer-preview-feature.adoc, docs/topics/installing-cli-tool.adoc, docs/topics/migration-paths.adoc, docs/topics/mta-cli-run.adoc
Initial draft of MTA-2613--migrating Window .NET apps to cross-platform .NET 8 apps.
Fixes: MTA-2613
See https://issues.redhat.com/browse/MTA-2613 for additional details.
For release(s): 7.1
QE Review: 
Signed-off-by: John Wilkins <jowilkin@redhat.com>
=> MTA-2613: [Documentation for] [Tech-Preview] Add support for analysis of .NET applications

docs/cli-guide/master.adoc, docs/topics/installing-cli-tool-disconnected.adoc
* [MTA-3245](https://issues.redhat.com/browse/MTA-3245)
=> MTA-3245: Document disconnected MTA CLI installation

docs/cli-guide/master.adoc, docs/topics/installing-mta-disconnected-environment.adoc, docs/topics/mta-cli-run.adoc
* [MTA-3245 - disconnected installation of MTA CLI](https://issues.redhat.com/browse/MTA-3245)
* [MTA disconnected installation](https://anarnold97.github.io/MTA-Preview/MTA/MTA-3245.html#installing-mta-disconnected-environment_cli-guide)
=> MTA-3245: Document disconnected usage of MTA CLI

docs/topics/new-mta-features.adoc
* [MTA new features](https://anarnold97.github.io/MTA-Preview/MTA/New-Features.html#new-mta-features_getting-started-guide)
=> WIP - New features for MTA 7.1.0

docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/topics/mta-web-assessing-apps.adoc
* [MTA-3573](https://issues.redhat.com/browse/MTA-3573)
* [7.4. Assessing an application](https://anarnold97.github.io/MTA-Preview/MTA/MTA-3573.html#mta-web-assessing-apps_user-interface-guide)
=> MTA-3573: Explain reason for potential false positives

docs/topics/con_automatic-tagging-of-an-application.adoc, docs/topics/mta-web-adding-applications.adoc, docs/topics/mta-web-edit-application.adoc, docs/topics/mta-what-is-the-toolkit.adoc, docs/web-console-guide/master.adoc
This MR adds content for the language discovery and technology discovery tasks. 
Fixes: MTA-3131
Issue: https://issues.redhat.com/browse/MTA-3131
For release(s): 7.1
QE Review: 
Signed-off-by: John Wilkins [jowilkin@redhat.com](mailto:jowilkin@redhat.com)
=> MTA-3131: [Documentation for] Automatic language and technology discovery for applications

docs/topics/mta-default-questionnaire.adoc, docs/topics/ref_yaml-template-for-custom-questionnaire.adoc
* [MTA-3638](https://issues.redhat.com/browse/MTA-3638)
* [[7.2.1. The default assessment questionnaire](https://docs.redhat.com/en/documentation/migration_toolkit_for_applications/7.0/html-single/user_interface_guide/index#mta-default-questionnaire_user-interface-guide) 
Copy link](https://anarnold97.github.io/MTA-Preview/MTA/collapse.html#mta-default-questionnaire_user-interface-guide)
=> MTA-3638: Put pathfinder.yaml into collapsible block

docs/topics/mta-7-configuration-web-console-on-ocp-local.adoc, docs/topics/mta-7-installing-web-console-on-ocp-local.adoc, docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/topics/templates/document-attributes.adoc, docs/web-console-guide/master.adoc
* [MTA-2850](https://issues.redhat.com/browse/MTA-2850)
* [MTA OCP Local](https://anarnold97.github.io/MTA-Preview/MTA/MTA-2850.html#mta-7-installing-web-console-on-ocp-local_user-interface-guide)
=> MTA-2850: Installing and Configuring OCP Local

docs/topics/mta-web-configuring-and-running-an-application-analysis.adoc, docs/topics/yaml-rule-structure-syntax.adoc
* [MTA-2696](https://issues.redhat.com/browse/MTA-2696)
Support for .NET language added
https://vsodhi.github.io/previews/MTA/MTA-2696.html#_rulesets
=> MTA-2696: Documentation for multilanguage support

docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/web-console-guide/master.adoc
* [Chapter 3. Installing the Migration Toolkit for Applications user interface](https://anarnold97.github.io/MTA-Preview/MTA/richard-PR.html#mta-7-installing-web-console-on-openshift_user-interface-guide)
Contents copied from https://github.com/migtools/mta-documentation/pull/25 to solve Richard's merge conflict.
Pull 25 approved by Dylan, Maayan, and Nandini.
=> Roles, Users, and Permissions in MTA for the mta-documentation repo

docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/topics/mta-requirements-for-java-analyzer.adoc, docs/web-console-guide/master.adoc
* [MTA-3416](https://issues.redhat.com/browse/MTA-3416)
* [Adding minimum requirements for Java analyzer and discovery](https://anarnold97.github.io/MTA-Preview/MTA/MTA-3416.html#mta-requirements-for-java-analyzer_user-interface-guide)
=> MTA-3416: Adding requirements for Java analyzer and discovery task

docs/cli-guide-mtr/master.adoc, docs/eclipse-code-ready-studio-guide-mtr/master.adoc, docs/getting-started-guide-mtr/master.adoc, docs/intellij-idea-plugin-guide-mtr/master.adoc, docs/maven-guide-mtr/master.adoc, docs/plugin-guide-mtr/master.adoc, docs/release-notes-mtr/master.adoc, docs/rules-development-guide-mtr/master.adoc, docs/topics/snippet-mtr-end-of-life.adoc, docs/vs-code-extension-guide-mtr/master.adoc, docs/web-console-guide-mtr/master.adoc
* [WINDUP-4225](https://issues.redhat.com/browse/WINDUP-4225)
* [CLI guide](https://anarnold97.github.io/MTA-Preview/MTR/end-of-life/cli-guide.html#introduction)
* [Eclipse guide](https://anarnold97.github.io/MTA-Preview/MTR/end-of-life/eclipse-guide.html#introduction_eclipse-code-ready-studio-guide)
* [Getting started guide](https://anarnold97.github.io/MTA-Preview/MTR/end-of-life/getting-started-guide.html#introduction)
* [IntelliJ guide](https://anarnold97.github.io/MTA-Preview/MTR/end-of-life/intellij-idea.html#introduction)
* [Maven guide](https://anarnold97.github.io/MTA-Preview/MTR/end-of-life/maven-guide.html#introduction)
* [Rules development guide](https://anarnold97.github.io/MTA-Preview/MTR/end-of-life/rules-development.html#introduction_rules-development-guide-mtr)
* [VS Code …
=> WINDUP-4225: MTR End of Life Admonition Added

docs/topics/templates/document-attributes.adoc
* [WINDUP-4215](https://issues.redhat.com/browse/WINDUP-4215)
```
:ProductVersion: 1.2.7
:PluginName: MTR plugin
:ProductDistributionVersion: 1.2.7.GA-redhat-00001
:ProductDistribution: mtr-1.2.7.GA-offline
```
=> WINDUP-4215: Attribute update for MTR 1.2.7

docs/topics/mta-about-console-guide.adoc, docs/topics/mta-about-the-intro-to-mta-guide.adoc
* [MTA-3844](https://issues.redhat.com/browse/MTA-3844)
=> Remove note about MTR

docs/topics/mta-7-installing-web-console-on-openshift.adoc
JIRA: https://issues.redhat.com/browse/MTA-3367
=> MTA-3367 RHSSO admin info

docs/topics/create-yaml-rule.adoc, docs/topics/yaml-rule-structure-syntax.adoc
JIRA: [MTA-3334](https://issues.redhat.com/browse/MTA-3334)
Initial google doc draft: https://docs.google.com/document/d/1pYq-3yVtaPSsD4Ybzuit_jqaN47JghKUSSoKQoGVops/edit
=> MTA-3334 -JAVA annotation

docs/eclipse-code-ready-studio-guide/master.adoc, docs/topics/adding-jboss-tools-dependencies-for-the-mta-plug-in.adoc, docs/topics/eclipse-installing-plugin.adoc, docs/topics/installing-eclipse.adoc, docs/topics/installing-java-development-kit.adoc
Tracked under [MTA-3533](https://issues.redhat.com/browse/MTA-3533)
The review can also be performed in the google doc. New procedures:
- [2.1. Installing Java Development Kit](https://docs.google.com/document/d/18L1eilLAz7wCzfjWOCC-WDASYuPRAzvSdS-oxXV_onE/edit#heading=h.5qyz93sz658i)
- [2.2. Installing Eclipse](https://docs.google.com/document/d/18L1eilLAz7wCzfjWOCC-WDASYuPRAzvSdS-oxXV_onE/edit#heading=h.nffldu6cems4)
- [2.3 Adding Jboss Tools dependencies for the MTA plug-in](https://docs.google.com/document/d/18L1eilLAz7wCzfjWOCC-WDASYuPRAzvSdS-oxXV_onE/edit#heading=h.v1y950pgl2wl)
Updated procedure (includes the Important note): 
- [2.4. Installing in a connected environment](https://docs.google.com/document/d/18L1eilLAz7wCzfjWOCC-WDASYuPRAzvSdS-oxXV_onE/edit#heading=h.ldadwsqkrerr)
=> [WIP] Adding new procedures to the Eclipse doc

docs/rules-development-guide/master.adoc
* [MTA-3858](https://issues.redhat.com/browse/MTA-3858)
* [Rules Dev Guide](https://anarnold97.github.io/MTA-Preview/MTA/rules-dev-guide.html)
=> MTA-3858: Removing XML sections of docs from Rules Dev Guide

docs/topics/mta-6-installing-web-console-on-openshift.adoc, docs/topics/mta-7-configuration-web-console-on-ocp-local.adoc, docs/topics/mta-7-installing-web-console-on-ocp-local.adoc, docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/topics/mta-requirements-for-java-analyzer.adoc, docs/topics/mta-rn-upgrade-notes-7-0-0.adoc, docs/topics/mta-rn-upgrade-notes-7-0-1.adoc, docs/topics/mta-rn-upgrade-notes-7-0-2.adoc
* [MTA-4234](https://issues.redhat.com/browse/MTA-4234)
Update GiB to Gi where applicable and Update GiB to GB where applicable
=> MTA-4234: Update GiB to Gi where applicable and Update GiB to GB where applicable

docs/topics/installing-cli-tool.adoc, docs/topics/mta-cli-analyze-multi-lang-apps.adoc, docs/topics/mta-cli-analyze.adoc, docs/topics/mta-cli-transform.adoc, docs/topics/mta-review-reports.adoc
Tracked under [MTA-4250](https://issues.redhat.com/browse/MTA-4250)
=> [To be merged for 7.1] QE feedback for the CLI guide

docs/topics/templates/document-attributes.adoc
* [MTA-3587](https://issues.redhat.com/browse/MTA-3587)
* [CLI guide](https://anarnold97.github.io/MTA-Preview/MTA/7.2.0-attributes.html)
| 7.2 | 7.2.0|
| --- | ---- |
| ![image](https://github.com/user-attachments/assets/c427fbbc-804d-4ffb-be06-61c8162508e8) | ![image](https://github.com/user-attachments/assets/3765109f-1165-4977-bc0d-68a7fe33278c) |
=> To be merged for 7.2 MTA-3587: Attributes update for 7.2.0

docs/release-notes/master.html, docs/topics/proc_running-the-containerless-mta-cli.adoc
* [MTA-4582](https://issues.redhat.com/browse/MTA-4582)
=> MTA-4582: Python3 not a requirement in CLI docs

docs/topics/mta-cli-run-multiple-apps.adoc
* [MTA-4590](https://issues.redhat.com/browse/MTA-4590)
=> MTA-4590: quick fix in formatting

docs/topics/mta-web-config-maven-repo.adoc
* [MTA-4684](https://issues.redhat.com/browse/MTA-4684)
* [4.3.3. Configuring a Maven repository and reducing its size](https://anarnold97.github.io/MTA-Preview/MTA/maven.html#configuring-maven-repositories)
=> MTA-4684: Remove note from docs/topics/mta-web-config-maven-repo.adoc

docs/cli-guide/master.adoc, docs/topics/installing-cli-tool.adoc, docs/topics/mta-cli-analyze.adoc, docs/topics/proc_running-the-containerless-mta-cli.adoc
Closes [MTA-4591](https://issues.redhat.com/browse/MTA-4591)
=> to be merged - [7.2.1] Adjustments for the CLI guide

docs/topics/about-the-mta-operator.adoc, docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/topics/templates/document-attributes.adoc
* [MTA-4600](https://issues.redhat.com/browse/MTA-4600)
| getting-started-guide preview | web-console-guide preview  |
|------------- |--------- |
| ![image](https://github.com/user-attachments/assets/ccc5f20a-2a97-4048-a710-73cd875bf4ef) | ![image](https://github.com/user-attachments/assets/dec110d7-a598-4b34-b4a1-c32787e6a82b) |
=> ready to be merged - MTA-4600: Updating the OCP references to be an attribute

docs/topics/configuring-kantra-directory.adoc, docs/vs-code-extension-guide/master.adoc
Closes [MTA-4692](https://issues.redhat.com/browse/MTA-4692).
=> to be merged - [MTA-4692] Procedure for configuring the .kanta directory

docs/topics/analyzer-rbac-snippet.adoc, docs/topics/installing-cli-tool.adoc, docs/topics/mta-rn-upgrade-notes-7-0-1.adoc, docs/topics/mta-rn-upgrade-notes-7-0-2.adoc, docs/topics/snippet-mtr-end-of-life.adoc
* [MTA-4781](https://issues.redhat.com/browse/MTA-4781)
=> MTA-4781Removing titles from admonitions

docs/topics/templates/document-attributes.adoc
@istein1 - please can you approve this PR
Once approved, I will sync and merge, before publishing
=> Updating the supported version of {OCP} to 4.18

docs/topics/mavenize.adoc
* [MTA-4914](https://issues.redhat.com/browse/MTA-4914)
=> MTA-4914: broken link to maven docs

docs/release-notes/master.adoc, docs/topics/ref_known-issues-7-2-2.adoc, docs/topics/ref_resolved-issues-7-2-2.adoc, docs/topics/templates/document-attributes.adoc
* [MTA-4505 Release Notes for 7.2.2](https://issues.redhat.com/browse/MTA-4505)
*  [MTA-4504 Attributes Update for 7.2.2](https://issues.redhat.com/browse/MTA-4504)
* 7.2.2
* [Release Notes](https://file.corp.redhat.com/pkylasam/rn-7.2.2/html-single/)
The peer review MTA for release notes 7.2.2 was completed in PR #98.
=> MTA-4505 Release Notes and Attributes Update for 7.2.2

docs/topics/mta-cli-analyze.adoc
* [MTA-4789](https://issues.redhat.com/browse/MTA-4789)
* 7.2.2
* [Performing Analysis Using Command Line](https://file.corp.redhat.com/pkylasam/mta-4789/html-single/#mta-cli-analyze_cli-guide)
=> TO BE MERGED FOR 7.2.2: MTA-4789: Failed to get dependencies from compiled Java binaries

docs/topics/mta-cli-analyze-unsupported-provider.adoc
* [MTA-4904](https://issues.redhat.com/browse/MTA-4904)
* [2.5.2. Analyzing a multi-language application for an unsupported language provider](https://anarnold97.github.io/MTA-Preview/MTA/MTA-4904-override-provider-setting.html#mta-cli-analyze-unsupported-provider_cli-guide)
=> MTA-4904: Clarify  `--override-provider-setting`

docs/topics/installing-cli-tool.adoc, docs/topics/snippet_jdk-hardware-mac-prerequisites.adoc, docs/topics/templates/document-attributes.adoc
* [MTA-4887](https://issues.redhat.com/browse/MTA-4887)
[2.1. Installing the CLI](https://anarnold97.github.io/MTA-Preview/MTA/devel-package.html#installing-cli-tool_cli-guide)
=> MTA-4887: Ensure that JDK requirements for RHEL & Fedora indicate to install Development package

docs/release-notes/master.adoc, docs/topics/ref_known-issues-7-3-0.adoc
* [MTA-5229](https://issues.redhat.com/browse/MTA-5229)
* 7.3.0
* [.NET application analysis fails on the MTA CLI](https://file.corp.redhat.com/pkylasam/mta-5229/html-single/#known-issues-7-3-0_release-notes)
=> MTA-5229: Known issue of .NET application analysis in 7.3.0

docs/cli-guide/master-docinfo.xml, docs/topics/mta-web-configuring-and-running-an-application-analysis.adoc, docs/topics/mta-web-creating-custom-migration-targets.adoc
Tracked under [MTA-4549](https://issues.redhat.com/browse/MTA-4549).
=> [WIP] Mentions of Python/Node.js support for MTA 7.3.0

docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/topics/templates/document-attributes.adoc
* [MTA-4540 Keycloak Migrate to Red Hat Build of Keycloak](https://issues.redhat.com/browse/MTA-4540)
* 7.3.0
* [Red Hat Build of Keycloak Updates](https://file.corp.redhat.com/pkylasam/mta-4540/html-single/#mta-7-red-hat-build-of-keycloak_user-interface-guide)
=> MTA-4540 Red Hat Build of Keycloak

docs/topics/templates/document-attributes.adoc
* [MTA-4515](https://issues.redhat.com/browse/MTA-4515)
=> MTV-4515 Attributes Update for MTA 7.3.0

docs/topics/templates/document-attributes.adoc
* [MTA-5286](https://issues.redhat.com/browse/MTA-5286)
* 7.2.3
=> MTA-5286 Attribute Updates for MTA 7.2.3

docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/topics/mta-requirements-for-java-analyzer.adoc
* [MTA-5404](https://issues.redhat.com/browse/MTA-5404)
* 7.2
=> 7.2 - MTA-5404 Modified Java provider memory requirement

docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/topics/mta-requirements-for-java-analyzer.adoc
* [MTA-5602](https://issues.redhat.com/browse/MTA-5602)
* 7.3.1
* [3.2. Installing the Migration Toolkit for Applications Operator and the user interface](https://pkylas007.github.io/Preview/MTA/mta-5040/index.html#installing-mta-operator-and-ui_user-interface-guide)
* [3.5. Adding minimum requirements for Java analyzer and discovery](https://pkylas007.github.io/Preview/MTA/mta-5040/index.html#mta-requirements-for-java-analyzer_user-interface-guide)
=> MTA-5404 Modified Java provider memory requirement

docs/topics/templates/document-attributes.adoc
* [MTA-4809](https://github.com/migtools/mta-documentation/pull/161)
* 7.3.1
* [Attribute update for 7.3.1](https://file.corp.redhat.com/pkylasam/mta-4809/html-single/)
=> MTA-4809 Attribute Updates for 7.3.1

docs/topics/mta-rn-technical-changes-7-3-2.adoc
=> MTA 7.3.2 Release Notes - Modified deprecation notice

docs/topics/mta-7-installing-web-console-on-openshift.adoc, docs/web-console-guide/master.adoc
* 8.0.0
* [Table 3.1. Required persistent volumes](https://pkylas007.github.io/Preview/MTA/dl-database/index.html#mta-7-installing-web-console-on-openshift_user-interface-guide)
=> Corrected the Developer Lightspeed database name

docs/topics/ref_new-features-and-enhancements-8-0.adoc, docs/topics/ref_tech-previews-8-0.adoc
* [MTA-6212](https://issues.redhat.com/browse/MTA-6212)
* 8.0.0
* [Release notes 8.0.0](https://pkylas007.github.io/Preview/MTA/release-notes/index.html)
=> MTA 8.0.0 - Fixed errors

docs/topics/developer-lightspeed/assembly_solution-server-configurations.adoc, docs/topics/developer-lightspeed/con_developer-lightspeed-pathways.adoc, docs/topics/developer-lightspeed/con_intro-to-developer-lightspeed.adoc, docs/topics/developer-lightspeed/con_llm-service-openshift-ai.adoc, docs/topics/developer-lightspeed/con_persistent-volumes.adoc, docs/topics/developer-lightspeed/con_prerequisites.adoc, docs/topics/developer-lightspeed/proc_apply-rag-resolution.adoc, docs/topics/developer-lightspeed/proc_configuring-developer-lightspeed-ide-settings.adoc, docs/topics/developer-lightspeed/proc_configuring-developer-profile-settings.adoc, docs/topics/developer-lightspeed/proc_configuring-solution-server-settings-file.adoc, docs/topics/developer-lightspeed/proc_tackle-enable-dev-lightspeed.adoc, docs/topics/developer-lightspeed/proc_tackle-llm-secret.adoc
* 8.0.0
* [Preview of capitalization and link changes](https://pkylas007.github.io/Preview/MTA/dev-lightspeed-updates/index.html)
This PR contains no content change.
=> Made minor style and link changes
